spring.application.name=ruchesConnecteSpringboot
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=8080

# url bdd
firebase.database-url=https://esp32-bd-8ac4d-default-rtdb.europe-west1.firebasedatabase.app/

# credentials json dans resources/firebase/
firebase.credentials.classpath=/firebase/esp32-bd-service-account.json

# --- Firebase Auth REST ---
firebase.apiKey=AIzaSyAgaAgBG95VTOu0ntyqpK5LkcBjPbli-n4

# URL post-login
app.login.success-url=/ruchers

